//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by adgui.rc
//
#define DO_MENU                         1
#define IDS_CAPTION                     1
#define IDNEXT                          6
#define IDFINISHED                      7
#define IDCANCEL2                       8
#define IDI_SPR                         105
#define IDR_MENU                        121
#define IDD_ABOUT                       122
#define IDD_EDIT_ATTRIBS                123
#define IDD_ARG                         125
#define IDD_REPORT_FILE                 127
#define IDD_REPORT_DEP                  128
#define IDD_REPORT_IND                  129
#define IDD_ARGSET                      130
#define IDC_SQUIRREL                    1000
#define IDC_LIST_ATTRIBS                1002
#define IDC_LIST_ATTVALS                1003
#define IDC_CHECK_SYMBOLIC              1005
#define IDC_CHECK_REAL                  1006
#define IDC_EDIT_NUM                    1009
#define IDC_EDIT_INT                    1009
#define IDC_SPIN                        1010
#define IDC_SPIN_INT                    1010
#define IDC_DROP_STRING                 1012
#define IDC_ARG_DESCRIPTION             1013
#define IDC_EDIT_ARG                    1014
#define IDC_SELECT_SYMBOLIC             1017
#define IDC_SELECT_REAL                 1018
#define IDC_SELECT_INVERT               1020
#define IDC_RENAME_ATT                  1021
#define IDC_NEW                         1022
#define IDC_RENAME_VAL                  1023
#define IDC_NEW_VAL                     1024
#define IDC_SELECT_ALL                  1025
#define IDC_DELETE                      1026
#define IDC_EDIT                        1027
#define IDC_BUTTON1                     1028
#define IDC_DEFINE                      1028
#define IDC_BROWSE                      1028
#define IDC_CHECK_GRAPH                 1029
#define IDC_AGGREGATE                   1029
#define IDC_DELETE_VAL                  1030
#define IDC_CHECK_TEXT                  1030
#define IDC_CHECK_FILE                  1031
#define IDC_EDIT_FILE                   1032
#define IDC_RADIO_CUMNONE               1033
#define IDC_RADIO_SUM                   1034
#define IDC_RADIO_PROD                  1035
#define IDC_RADIO_MEAN                  1036
#define IDC_RADIO_QUOT                  1037
#define IDC_RADIO_DIFF                  1038
#define IDC_RADIO_STDNONE               1040
#define IDC_RADIO_NONE                  1040
#define IDC_RADIO_PLUS                  1041
#define IDC_RADIO_ADD                   1041
#define IDC_RADIO_TIMES                 1042
#define IDC_RADIO_MULT                  1042
#define IDC_RADIO_AVG                   1043
#define IDC_RADIO_DIV                   1044
#define IDC_RADIO_MINUS                 1045
#define IDC_RADIO_SUB                   1045
#define IDC_DROP_ATT                    1046
#define IDC_DROP_VAL1                   1047
#define IDC_DROP_VAL2                   1048
#define IDC_LIST_VALS                   1049
#define IDC_RADIO_AVERAGE               1050
#define IDC_RADIO_TOTAL                 1051
#define IDC_RADIO_COUNT                 1052
#define IDC_RADIO_TALLY                 1053
#define IDC_STATIC_AND                  1055
#define IDC_LIST                        1056
#define IDC_RADIO_SYMBOLIC              1057
#define IDC_RADIO_REAL                  1058
#define MIN_MENU                        40001
#define ID_TOOLS_RULELEARNER            40001
#define ID_TOOLS_DECISIONLIST           40002
#define ID_TOOLS_BAYESNET               40003
#define ID_FILE_MYSAVE                  40004
#define ID_FILE_LOAD                    40005
#define ID_FILE_LOADTEST                40006
#define ID_FILE_JOIN                    40007
#define ID_FILE_CONCATENATE             40008
#define ID_FILE_QUIT                    40009
#define ID_VIEW_DATA                    40010
#define ID_VIEW_RULES                   40011
#define ID_VIEW_INFO                    40012
#define ID_VIEW_TABLE                   40013
#define ID_VIEW_MATRIX                  40014
#define ID_VIEW_ATTRIBUTE               40015
#define ID_VIEW_GRAPH                   40017
#define ID_DATA_EDITATTRIBUTES          40021
#define ID_DATA_SETINPUTS               40022
#define ID_DATA_SETOUTPUT               40023
#define ID_DATA_SORTRECORDS_RANDOMLY    40024
#define ID_DATA_SORTRECORDS_BYATTRIBUTE 40025
#define ID_DATA_REMOVERECORDS_MARKED    40026
#define ID_DATA_REMOVERECORDS_UNMARKED  40027
#define ID_DATA_REMOVERECORDS_DUPLICATES 40028
#define ID_DATA_MARKEDRECORDS_MARK      40029
#define ID_DATA_MARKEDRECORDS_SUBMARK   40030
#define ID_DATA_MARKEDRECORDS_UNMARK    40031
#define ID_DATA_MARKEDRECORDS_TOGGLE    40032
#define ID_DATA_MARKEDRECORDS_VIEW      40033
#define ID_DATA_SORTATTRIBUTES_SWAP     40038
#define ID_DATA_SORTATTRIBUTES_BYARITY_INCREASING 40039
#define ID_DATA_SORTATTRIBUTES_BYARITY_DECREASING 40040
#define ID_DATA_SORTATTRIBUTES_BYENTROPY_INCREASING 40041
#define ID_DATA_SORTATTRIBUTES_BYENTROPY_DECREASING 40042
#define ID_TOOLS_TREE_MAKE              40043
#define ID_TOOLS_TREE_CLEAR             40044
#define ID_TOOLS_TREE_FAST              40045
#define ID_TOOLS_TREE_SLOW              40046
#define ID_HELP_ABOUT                   40047
#define ID_TOOLS_FEATURES               40048
#define ID_FILE_BATCH                   40049
#define ID_DATA_ATTRIBUTETYPE_SYMBOLIZE 40051
#define ID_DATA_ATTRIBUTETYPE_REALIZE   40052
#define ID_VIEW_RECORDS                 40053
#define ID_FILE_COMPATIBLES             40054
#define ID_VIEW_PLOT                    40055
#define ID_TOOLS_CORRELATIONS           40056
#define ID_TOOLS_MARGINALS              40056
#define ID_VIEW_BRIEFING                40057
#define ID_DATA_SYMBOLIZEMISSING        40058
#define ID_PETFOOD_REPORTDATA_MEANEATEN 40062
#define ID_PETFOOD_REPORTDATA_WFRATIO   40063
#define ID_PETFOOD_CATSTAT              40064
#define ID_PETFOOD_CATRANK              40065
#define ID_PETFOOD_CATSIG               40066
#define ID_PETFOOD_RENAMEVALUES         40067
#define ID_PETFOOD_YESTERDAY_BUILDDATA  40070
#define ID_PETFOOD_YESTERDAY_SYMBOLIZE  40072
#define ID_PETFOOD_YESTERDAY_CLUSTERTESTING 40074
#define ID_PETFOOD_YESTERDAY_CLUMPTESTING 40074
#define ID_TOOLS_CHOWLIUTREES           40075
#define ID_TOOLS_COR_IND                40077
#define ID_TOOLS_CORRELATIONS_RANKINPUTSVSOUTPUT 40078
#define ID_TOOLS_CORRELATIONS_CROSSCORRELATION 40079
#define ID_TOOLS_CORRELATIONS_AUTOCORRELATION 40080
#define ID_PETFOOD_WHATSENOUGH          40081
#define ID_PETFOOD_YESTERDAY_NOISINESS  40082
#define MAX_MENU                        40200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40082
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
